// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Kairos/internal/models"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthStorage is a mock of AuthStorage interface.
type MockAuthStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStorageMockRecorder
}

// MockAuthStorageMockRecorder is the mock recorder for MockAuthStorage.
type MockAuthStorageMockRecorder struct {
	mock *MockAuthStorage
}

// NewMockAuthStorage creates a new mock instance.
func NewMockAuthStorage(ctrl *gomock.Controller) *MockAuthStorage {
	mock := &MockAuthStorage{ctrl: ctrl}
	mock.recorder = &MockAuthStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStorage) EXPECT() *MockAuthStorageMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthStorage) CreateUser(ctx context.Context, user models.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthStorageMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthStorage)(nil).CreateUser), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockAuthStorage) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockAuthStorageMockRecorder) GetUserByLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockAuthStorage)(nil).GetUserByLogin), ctx, login)
}

// MockCoreStorage is a mock of CoreStorage interface.
type MockCoreStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCoreStorageMockRecorder
}

// MockCoreStorageMockRecorder is the mock recorder for MockCoreStorage.
type MockCoreStorageMockRecorder struct {
	mock *MockCoreStorage
}

// NewMockCoreStorage creates a new mock instance.
func NewMockCoreStorage(ctrl *gomock.Controller) *MockCoreStorage {
	mock := &MockCoreStorage{ctrl: ctrl}
	mock.recorder = &MockCoreStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreStorage) EXPECT() *MockCoreStorageMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockCoreStorage) CancelBooking(tx *sql.Tx, ctx context.Context, bookingID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", tx, ctx, bookingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockCoreStorageMockRecorder) CancelBooking(tx, ctx, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockCoreStorage)(nil).CancelBooking), tx, ctx, bookingID)
}

// Close mocks base method.
func (m *MockCoreStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCoreStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCoreStorage)(nil).Close))
}

// CreateBooking mocks base method.
func (m *MockCoreStorage) CreateBooking(tx *sql.Tx, ctx context.Context, booking *models.Booking) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", tx, ctx, booking)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockCoreStorageMockRecorder) CreateBooking(tx, ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockCoreStorage)(nil).CreateBooking), tx, ctx, booking)
}

// CreateEvent mocks base method.
func (m *MockCoreStorage) CreateEvent(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockCoreStorageMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockCoreStorage)(nil).CreateEvent), ctx, event)
}

// GetAllEvents mocks base method.
func (m *MockCoreStorage) GetAllEvents(ctx context.Context) ([]models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEvents", ctx)
	ret0, _ := ret[0].([]models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEvents indicates an expected call of GetAllEvents.
func (mr *MockCoreStorageMockRecorder) GetAllEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEvents", reflect.TypeOf((*MockCoreStorage)(nil).GetAllEvents), ctx)
}

// GetBookingForConfirm mocks base method.
func (m *MockCoreStorage) GetBookingForConfirm(tx *sql.Tx, ctx context.Context, userID int64, eventUUID string) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingForConfirm", tx, ctx, userID, eventUUID)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingForConfirm indicates an expected call of GetBookingForConfirm.
func (mr *MockCoreStorageMockRecorder) GetBookingForConfirm(tx, ctx, userID, eventUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingForConfirm", reflect.TypeOf((*MockCoreStorage)(nil).GetBookingForConfirm), tx, ctx, userID, eventUUID)
}

// GetEventForBooking mocks base method.
func (m *MockCoreStorage) GetEventForBooking(tx *sql.Tx, ctx context.Context, eventUUID string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventForBooking", tx, ctx, eventUUID)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventForBooking indicates an expected call of GetEventForBooking.
func (mr *MockCoreStorageMockRecorder) GetEventForBooking(tx, ctx, eventUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventForBooking", reflect.TypeOf((*MockCoreStorage)(nil).GetEventForBooking), tx, ctx, eventUUID)
}

// GetInfo mocks base method.
func (m *MockCoreStorage) GetInfo(ctx context.Context, eventUUID string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, eventUUID)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockCoreStorageMockRecorder) GetInfo(ctx, eventUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockCoreStorage)(nil).GetInfo), ctx, eventUUID)
}

// Transaction mocks base method.
func (m *MockCoreStorage) Transaction(ctx context.Context, fn func(*sql.Tx, context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockCoreStorageMockRecorder) Transaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockCoreStorage)(nil).Transaction), ctx, fn)
}

// UpdateBookingStatus mocks base method.
func (m *MockCoreStorage) UpdateBookingStatus(tx *sql.Tx, ctx context.Context, bookingID int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", tx, ctx, bookingID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockCoreStorageMockRecorder) UpdateBookingStatus(tx, ctx, bookingID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockCoreStorage)(nil).UpdateBookingStatus), tx, ctx, bookingID, status)
}

// UpdateEventSeats mocks base method.
func (m *MockCoreStorage) UpdateEventSeats(tx *sql.Tx, ctx context.Context, increment bool, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventSeats", tx, ctx, increment, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventSeats indicates an expected call of UpdateEventSeats.
func (mr *MockCoreStorageMockRecorder) UpdateEventSeats(tx, ctx, increment, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventSeats", reflect.TypeOf((*MockCoreStorage)(nil).UpdateEventSeats), tx, ctx, increment, eventID)
}
