// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Kairos/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockBroker) Consume() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Consume")
}

// Consume indicates an expected call of Consume.
func (mr *MockBrokerMockRecorder) Consume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockBroker)(nil).Consume))
}

// Produce mocks base method.
func (m *MockBroker) Produce(booking *models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockBrokerMockRecorder) Produce(booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockBroker)(nil).Produce), booking)
}

// SetCancelFunc mocks base method.
func (m *MockBroker) SetCancelFunc(fn func(context.Context, int64) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCancelFunc", fn)
}

// SetCancelFunc indicates an expected call of SetCancelFunc.
func (mr *MockBrokerMockRecorder) SetCancelFunc(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelFunc", reflect.TypeOf((*MockBroker)(nil).SetCancelFunc), fn)
}

// Shutdown mocks base method.
func (m *MockBroker) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockBrokerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockBroker)(nil).Shutdown))
}
